version: 2
updates:
- package-ecosystem: nuget
  directory: "/TFA.Web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jQuery
    versions:
    - 3.5.1
- package-ecosystem: nuget
  directory: "/TFA.Web.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Moq
    versions:
    - 4.16.0
